# Freemarker
spring:
  freemarker:
    cache: false
    charset: UTF-8

#    url: jdbc:mysql://192.168.117.130:3306/spring4 # Library
# Database
  datasource:
    url: jdbc:mysql://192.168.206.128:3306/spring4 # Home
    email: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

#jpa
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      jadira.usertype.autoRegisterUserTypes: true

#security
security:
  basic:
    enabled: false